### ISSUE TITLE
Cuid2 Parse

### ISSUE THREAD

**Issue by chrisjmccrum** [visus-io/cuid.net#28]
Can you add support to Parse strings into Cuid2 (similar to the current legacy Cuid behavior)?

**Comment by xaevik** [comment]
Hi @chrisjmccrum,

Unfortunately, no. Unlike `Cuid2` which has a fixed length and discernable parts which can be extracted and thus verifiable to a degree (this is why it can be instantiated from a string), `Cuid2` does not.

`Cuid2` has a variable length and is non-discernable by design so one cannot determine when, where, or how it was created. This was intentional on the original author's part and one of the driving factors as to why version 1 was deprecated in favor of version 2.

The best one can do is use a regular expression to fuzzy match whether a string *might* be a `Cuid2` value (which is what the [Java](https://github.com/thibaultmeyer/cuid-java/blob/c55aa797b13348a01ad1a059fe88a5af1c613e8f/src/main/java/io/github/thibaultmeyer/cuid/CUID.java#L116) port does to some degree). Such a method was not added to this port (and why `IComparable` and `IComparable<T>` where not implemented) because of this as there is no real concrete way to assert that a given string is a valid `Cuid2` and not just some randomly generated Base 36 string.
